### ISSUE TITLE
Navbar dropdown being overlayed by page content

### ISSUE THREAD

**Issue by dc143c** [qwikerx/flowbite-qwik#219]
Hey, there!

On a mobile breakpoint, the Navbar with dropdown doesn't work as expected. It's being overlayed by the content in the page.
You can check it on my page here: 
https://tesereft-git-new-designs-tesereft.vercel.app/

Code:
Navbar.tsx:
```import { component$ } from "@builder.io/qwik";
import { useLocation } from "@builder.io/qwik-city";
import { Button, DarkModeToggle, Navbar } from "flowbite-qwik";

export default component$(() => {
  const { url } = useLocation()
  return (
    <Navbar fluid class="text-sm">
      <Navbar.Brand href="/">
        <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">Tesereft</span>
      </Navbar.Brand>
      <Navbar.Toggle />
      <Navbar.Collapse>
        <Navbar.Link href="/" active={url.pathname === '/'}>
          Home
        </Navbar.Link>
        <Navbar.Link href="/about" active={url.pathname === '/about/'}>
          About Us
        </Navbar.Link>
        <Navbar.Link href="/cases" active={url.pathname === '/cases/'}>Cases</Navbar.Link>
      </Navbar.Collapse>
      <Navbar.Collapse>
        <Button color="light" pill>
          Login
        </Button>
        <DarkModeToggle />
      </Navbar.Collapse>
    </Navbar>
  );
});```

Layout.tsx:
```import { component$, Slot } from "@builder.io/qwik";
import type { RequestHandler } from "@builder.io/qwik-city";
import Footer from "~/components/footer";
import Navbar from "~/components/navbar";

export const onGet: RequestHandler = async ({ cacheControl }) => {
  // Control caching for this request for best performance and to reduce hosting costs:
  // https://qwik.dev/docs/caching/
  cacheControl({
    // Always serve a cached response by default, up to a week stale
    staleWhileRevalidate: 60 * 60 * 24 * 7,
    // Max once every 5 seconds, revalidate on the server to get a fresh version of this page
    maxAge: 5,
  });
};

export default component$(() => {
  return (
    <>
    <div class="z-50 bg-white">
      <Navbar />
    </div>
    <div class="z-10 bg-white">
      <Slot />
    </div>
    <Footer />
    </>
  );
});```

Can repo on Chrome and Firefox.

**Comment by dc143c** [comment]
Fixed implementing like this:
```

    <Navbar fluid class="text-sm" sticky>
      <Navbar.Brand href="/">
        <span class="self-center whitespace-nowrap text-xl font-semibold dark:text-white">
          <img src="/images/logo.svg" alt="Tesereft" class="w-10 h-10" />
        </span>
      </Navbar.Brand>

      <div class="flex space-x-3 gap-2 md:order-2 md:space-x-0 rtl:space-x-reverse items-center justify-center">
        <Button color="alternative" href={`/${locale === "pt-br" ? "en" : "pt-br"}/`}>
          {locale === "pt-br" ? "🇺🇸" : "🇧🇷"}
        </Button>
        <DarkModeToggle />
        <Navbar.Toggle />
      </div>
      <Navbar.Collapse class="mb-2 md:mb-0">
        <Navbar.Link href={`/`} active={url.pathname === '/'}>
          {$localize`Home`}
        </Navbar.Link>
        <Navbar.Link href={`/${locale}/about`} active={url.pathname.includes('/about')}>
          {$localize`About Us`}
        </Navbar.Link>
        <Navbar.Link href={`/${locale}/cases`} active={url.pathname.includes('/cases/')}>
          {$localize`Cases`}
        </Navbar.Link>
      </Navbar.Collapse>
    </Navbar>
   ```

**Comment by jcfauchet** [comment]
Hi @dc143c,
Thank you for reporting this issue.
Does the bug still persist?
If so, we can look into it for the next release.
